Rename bootstrap to setup, add update/setup .ps1
Signed-off-by: Christopher Larson <kergoth@gmail.com>

diff --git a/script/update b/script/update
--- a/script/update
+++ b/script/update
@@ -30,16 +30,16 @@ fi
 tmpfile=$(mktemp -t "${0##*/}.XXXXXX")
 trap on_exit EXIT INT TERM
 
-if ! command -v nix >/dev/null 2>&1; then
-    echo >&2 "Error: nix must be installed to update"
-    exit 1
-fi
-
 echo >&2 "Updating chezmoi"
 chezmoi upgrade
 
 echo >&2 "Updating dotfiles repository"
 chezmoi update -R
+
+if ! command -v nix >/dev/null 2>&1; then
+    echo >&2 "Error: nix must be installed to update Home Manager packages"
+    exit 1
+fi
 
 echo >&2 "Updating Home Manager packages"
 cd ~/.config/home-manager
