Update
Signed-off-by: Christopher Larson <kergoth@gmail.com>

diff --git a/home/dot_config/zsh/dot_zshenv.tmpl b/home/dot_config/zsh/dot_zshenv.tmpl
--- a/home/dot_config/zsh/dot_zshenv.tmpl
+++ b/home/dot_config/zsh/dot_zshenv.tmpl
@@ -55,11 +55,25 @@ export DOCKER_CONFIG="$XDG_CONFIG_HOME"/docker
 export MACHINE_STORAGE_PATH="$XDG_DATA_HOME"/docker-machine
 export RANDFILE=$XDG_DATA_HOME/rng
 export PARALLEL_HOME="$XDG_CONFIG_HOME"/parallel
+export LESSHISTFILE=$XDG_STATE_HOME/lesshst
+export _FASD_VIMINFO=$XDG_DATA_HOME/vim/viminfo
+export _FASD_DATA=$XDG_DATA_HOME/fasd/data
+export _ZO_DATA_DIR=$XDG_DATA_HOME/zoxide
 export CFLAGS=-O2
 export XZ_DEFAULTS=--threads=0
 export PAGER=more
 export YSU_IGNORED_ALIASES=("vi")
 export SHELLCHECK_OPTS="-e SC2002 -e SC2039 -e SC2209"
+
+# Rust
+export CARGO_HOME="$XDG_DATA_HOME/cargo"
+export CARGO_INSTALL_ROOT="${XDG_DATA_HOME%/*}"
+export RUSTUP_HOME="$XDG_DATA_HOME/rustup"
+
+# Python
+export WORKON_HOME=$XDG_DATA_HOME/virtualenvs
+export PIP_DOWNLOAD_CACHE=$XDG_CACHE_HOME/pip
+export POETRY_HOME=~/.poetry
 
 # Skip compinit in system zshrc on some hosts
 skip_global_compinit=1
@@ -83,6 +97,48 @@ fi
 export GHQ_ROOT=~/Repos
 # git-get repository path
 export GIT_PATH=~/Repos
+
+# Fix SSH auth socket location so agent forwarding works with tmux and VS Code
+if [ -n "$SSH_AUTH_SOCK" ] && [ -e "$HOME/.ssh/auth_sock" ] && [ "$SSH_AUTH_SOCK" != "$HOME/.ssh/auth_sock" ]; then
+    export SSH_AUTH_SOCK="$HOME/.ssh/auth_sock"
+fi
+
+if [[ ! -e /.dockerenv ]]; then
+    case "$(uname -r)" in
+        *-Microsoft)
+            OSTYPE=WSL
+            WSLVER=1
+            export USERPROFILE="${USERPROFILE:-$(wslpath "$(cmd.exe /D /C 'SET /P <NUL=%USERPROFILE%' 2>/dev/null)")}"
+            if [[ -z "$SSH_AUTH_SOCK" ]] && [[ -n "$WSL_AUTH_SOCK" ]]; then
+                export SSH_AUTH_SOCK=$WSL_AUTH_SOCK
+            fi
+            ;;
+        *-microsoft-*)
+            OSTYPE=WSL
+            WSLVER=2
+            export USERPROFILE="${USERPROFILE:-$(wslpath "$(cmd.exe /D /C 'SET /P <NUL=%USERPROFILE%' 2>/dev/null)")}"
+            if [[ -z "${NPIPERELAY:-}" ]]; then
+                for i in "$USERPROFILE/Apps/npiperelay/npiperelay.exe" "$USERPROFILE/scoop/apps/npiperelay/current/npiperelay.exe"; do
+                    if [[ -e "$i" ]]; then
+                        NPIPERELAY="$i"
+                        break
+                    fi
+                done
+            fi
+            if [[ -e "${NPIPERELAY:-}" ]]; then
+                if (( $+commands[socat] )); then
+                    export SSH_AUTH_SOCK=$HOME/.ssh/agent.sock
+                    if ! ss -a | grep -q "$SSH_AUTH_SOCK"; then
+                        rm -f "$SSH_AUTH_SOCK"
+                        ( setsid socat "UNIX-LISTEN:$SSH_AUTH_SOCK,fork" EXEC:"$NPIPERELAY -ei -s //./pipe/openssh-ssh-agent",nofork & )
+                    fi
+                else
+                    echo >&2 "Warning: socat is not installed, unable to use npiperelay for ssh auth sock"
+                fi
+            fi
+            ;;
+    esac
+fi
 
 for i in $XDG_CONFIG_HOME/*/env.zsh(N); do
     . "$i"
